### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by kadirburlukkara** [philipp-kurz/Metin2-Bot#1]
hello, is there a guide on how to use the bot and how to download it, thanks

**Comment by MBogdanski** [comment]
Hi. To run this bot you just simply download code through ZIP or Git, install requirements from txt file, then just run main.py using python command. But the problem is Philipp created bot based on event Snow metins, so to run it to classic or other metins you should specify your own HSV Filters or train models through Cascade Classifiers

**Comment by Scapta0** [comment]
yardımcı olur musunuz bir video ile

> Merhaba. Bu botu çalıştırmak için kodu ZIP veya Git üzerinden indirmeniz, gereksinimleri txt dosyasından yüklemeniz ve ardından python komutunu kullanarak main.py'yi çalıştırmanız yeterlidir. Ancak sorun, Philipp'in olay Kar metinlerine dayalı olarak yarattığı bottur, bu yüzden onu klasik veya diğer metinlere çalıştırmak için kendi HSV Filtrelerinizi belirtmeli veya Modelleri Kademeli Sınıflandırıcılar aracılığıyla eğitmelisiniz

**Comment by Scapta0** [comment]
video ile gösterir misin

**Comment by Scapta0** [comment]
bu konuda yardım edermisin

**Comment by mrarevio** [comment]
Can any one help me i get this Error:

Traceback (most recent call last):
  File "c:\Metin2 Farmer\metin_farm_bot\main.py", line 3, in <module>
    from captureAndDetect import CaptureAndDetect
  File "c:\Metin2 Farmer\metin_farm_bot\captureAndDetect.py", line 2, in <module>
    from utils import Vision, SnowManFilter
ImportError: cannot import name 'Vision' from 'utils' (C:\Users\brand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\utils\__init__.py)
